version: "3"
   
services:
    postgresdb:
        image: postgres
        restart: on-failure
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - PGDATA=/var/lib/postgresql/data/database
        volumes:
            - ./db_data:/var/lib/postgresql/data/database
        ports:
            - "5432:5432"
    phppgadmin:
        image: docker.io/bitnami/phppgadmin:7
        ports:
            - '5080:8080'
            - '50443:8443'
        environment:
            - DATABASE_HOST=postgresdb
        depends_on:
            - postgresdb
    permissions:
        build: .
        restart: always
        ports:
        - "8082:8082"
        depends_on: 
            - postgresdb
        volumes:
            - ./certs:/project/certs
    